<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $value =  array(
            ['nama' => "BANK BRI"],
            ['nama' => "BANK BNI"],
            ['nama' => "BANK BTN"],
            ['nama' => "MANDIRI"],
            ['nama' => "BANK ACEH"],
            ['nama' => "BANK SYARIAH"],
            ['nama' => "BANK AGRO"],
            ['nama' => "BANK ARTHA GRAHA"],
            ['nama' => "BANK ARTOS"],
            ['nama' => "BANK BENGKULU"],
            ['nama' => "BANK BJB"],
            ['nama' => "BANK BNP"],
            ['nama' => "BANK BPD DIY"],
            ['nama' => "BANK BPD DIY SYARIAH"],
            ['nama' => "BANK BTPN"],
            ['nama' => "BANK BUKOPIN"],
            ['nama' => "BANK BUMI ARTA"],
            ['nama' => "BANK CAPITAL"],
            ['nama' => "Baank China Construction Bank Indonesia"],
            ['nama' => "BANK DKI"],
            ['nama' => "BANK EKA"],
            ['nama' => "BANK GANESHA"],
            ['nama' => "BANK HSBC Indonesia"],
            ['nama' => "BANK INA"],
            ['nama' => "BANK INDEX"],
            ['nama' => "BANK JAMBIL"],
            ['nama' => "BANK JASA JAKARTA"],
            ['nama' => "BANK JATENG"],
            ['nama' => "BANK JATIM"],
            ['nama' => "BANK KALBAR"],
            ['nama' => "BANK KALSEL"],
            ['nama' => "BANK KALSEL SYARIAH"],
            ['nama' => "BANK KALTENG"],
            ['nama' => "BANK KALTIM"],
            ['nama' => "BANK KALTIM SYARIAH"],
            ['nama' => "BANK KESEJAHTERAAN"],
            ['nama' => "BANK LAMPUNG"],
            ['nama' => "BANK MALUKU"],
            ['nama' => "BANK MAS"],
            ['nama' => "BANK MASPION"],
            ['nama' => "BANK MAYAPADA"],
            ['nama' => "BANK MAYORA"],
            ['nama' => "BANK MEGA"],
            ['nama' => "BANK MEGA SYARIAH"],
            ['nama' => "BANK MESTIKA"],
            ['nama' => "BANK MUAMALAT"],
            ['nama' => "BANK NAGARI"],
            ['nama' => "BANK NTB"],
            ['nama' => "BANK NTT"],
            ['nama' => "BANK OF CHINA"],
            ['nama' => "BANK OF INDIA INDONESIA"],
            ['nama' => "BANK OF TOKYO-MITSUBISHI UFJ"],
            ['nama' => "BANK OKE"],
            ['nama' => "BANK PANIN DUBAI SYARIAH"],
            ['nama' => "BANK PAPUA"],
            ['nama' => "BANK RIAU KEPRI"],
            ['nama' => "BANK SAHABAT SAMPOERNA"],
            ['nama' => "BANK SBI"],
            ['nama' => "BANK SINARMAS"],
            ['nama' => "BANK SULSELBAR"],
            ['nama' => "BANK SULTENG"],
            ['nama' => "BANK SULUT"],
            ['nama' => "BANK SUMSELBABEL"],
            ['nama' => "BANK SUMUT"],
            ['nama' => "BANK SYARIAH BUKOPIN"],
            ['nama' => "BANK VICTORIA"],
            ['nama' => "BANK VICTORIA SYARIAH"],
            ['nama' => "BANK WOORI SAUDARA"],
            ['nama' => "BANK YUDHA BAKTI"],
            ['nama' => "BCA"],
            ['nama' => "BCA SYARIAH"],
            ['nama' => "BII MAYBANK"],
            ['nama' => "BPD BALI"],
            ['nama' => "BPD BANTENT"],
            ['nama' => "BPR KS"],
            ['nama' => "BRI SYARIAH"],
            ['nama' => "BTN SYARIAH"],
            ['nama' => "BTPN SYARIAH"],
            ['nama' => "CIMB NIAGA"],
            ['nama' => "CIMB NIAGA SYARIAH"],
            ['nama' => "CITIBANK"],
            ['nama' => "COMMONWEALTH BANK"],
            ['nama' => "CTBC BANK"],
            ['nama' => "DANAMON"],
            ['nama' => "DBS"],
            ['nama' => "DBS/Eks-ANZ"],
            ['nama' => "ICBC"],
            ['nama' => "JTRUST BANK"],
            ['nama' => "KEB HANA BANK"],
            ['nama' => "MANDIRI SYARIAH"],
            ['nama' => "MNC BANK"],
            ['nama' => "NOBU NATIONAL BANK"],
            ['nama' => "OCBC NISP"],
            ['nama' => "PANIN BANK"],
            ['nama' => "PERMATA BANK"],
            ['nama' => "QNB KESAWAN"],
            ['nama' => "RABOLBANK"],
            ['nama' => "ROYAL BANK"],
            ['nama' => "STANDARD CHARTERED"],
            ['nama' => "TCASH"],
            ['nama' => "UOB"]
        );

        DB::table('banks')->insert($value);
    }
}
